name: push to s3

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  s3-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: s3 copy html files
        uses: docker://amazon/aws-cli:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        with:
          args: s3 cp /github/workspace/ s3://ex-resume --recursive --exclude '.github/*' --exclude '.git/*' --exclude '.gitignore'
      - name: s3 sync
        uses: docker://amazon/aws-cli:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        with:
          args: s3 sync /github/workspace s3://ex-resume --delete --exclude '.github/*' --exclude '.git/*' --exclude '.gitignore'