name: push to s3

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  s3-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: s3 sync
        uses: docker://amazon/aws-cli:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        with:
          args: s3 sync /github/workspace/html s3://${{secrets.AWS_S3_BUCKET}}